import './globals.css'
import { Inter, Satisfy } from 'next/font/google'
import Navigation from './components/navigation';
import FooterMod from './components/FooterMod';
import { CartContextProvider } from './store/cartContext';


const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartContextProvider>
        <Navigation />
        {children}
        <FooterMod />
        </CartContextProvider>
      </body>
    </html>
  )
}
